
function opcion(n){
  if(n==1){
    document.getElementById('opcion0').style='display:block';
    document.getElementById('opcion1').style='display:block';
    document.getElementById('opcion1').innerHTML="Camisas";
    document.getElementById('opcion2').style='display:block';
    document.getElementById('opcion2').innerHTML="Short";
    document.getElementById('opcion3').style='display:block';
    document.getElementById('opcion3').innerHTML="Chamaras";
    document.getElementById('opcion4').style='display:block';
    document.getElementById('opcion4').innerHTML="Bolsas";
    document.getElementById('opcion5').style='display:block';
    document.getElementById('opcion5').innerHTML="Legging";
    document.getElementById('opcion6').style='display:block';
    document.getElementById('opcion6').innerHTML="Faldas";
    document.getElementById('opcion7').style='display:block';
    document.getElementById('opcion7').innerHTML="Lociones";
    document.getElementById('opcion8').style='display:block';
    document.getElementById('opcion8').innerHTML="Mallas";
  }else if(n==2){
    document.getElementById('opcion0').style='display:block';
    document.getElementById('opcion1').style='display:block';
    document.getElementById('opcion1').innerHTML="Camisas";
    document.getElementById('opcion2').style='display:block';
    document.getElementById('opcion2').innerHTML="Short";
    document.getElementById('opcion3').style='display:block';
    document.getElementById('opcion3').innerHTML="Pantalon";
    document.getElementById('opcion4').style='display:block';
    document.getElementById('opcion4').innerHTML="Interior";
    document.getElementById('opcion5').style='display:block';
    document.getElementById('opcion5').innerHTML="Sweater";
    document.getElementById('opcion6').style='display:block';
    document.getElementById('opcion6').innerHTML="Gorra";
    document.getElementById('opcion7').style='display:block';
    document.getElementById('opcion7').innerHTML="Tennis";
    document.getElementById('opcion8').style='display:block';
    document.getElementById('opcion8').innerHTML="Billetera";
  }else{
    document.getElementById('opcion0').style='display:block';
    document.getElementById('opcion1').style='display:block';
    document.getElementById('opcion1').innerHTML="Camisas";
    document.getElementById('opcion2').style='display:block';
    document.getElementById('opcion2').innerHTML="Pijama";
    document.getElementById('opcion3').style='display:none';
    document.getElementById('opcion3').innerHTML="Pantalon";
    document.getElementById('opcion4').style='display:none';
    document.getElementById('opcion4').innerHTML="Interior";
    document.getElementById('opcion5').style='display:none';
    document.getElementById('opcion5').innerHTML="Sweater";
    document.getElementById('opcion6').style='display:none';
    document.getElementById('opcion6').innerHTML="Gorra";
    document.getElementById('opcion7').style='display:none';
    document.getElementById('opcion7').innerHTML="Tennis";
    document.getElementById('opcion8').style='display:none';
    document.getElementById('opcion8').innerHTML="Billetera";
  }
}
